apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    email: azure-alerts@builtwithcaffine.cloud
    privateKeySecretRef:
      name: letsencrypt-staging
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    solvers:
      - dns01:
          azureDNS:
            environment: AzurePublicCloud
            hostedZoneName: az.builtwithcaffine.cloud
            managedIdentity:
              clientID: "managedIdentityClientId"
            resourceGroupName: rg-builtwithcaffeine-hub-weu
            subscriptionID: b67e1026-b589-41e2-b41f-73f8803f71a0
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    email: azure-alerts@builtwithcaffine.cloud
    privateKeySecretRef:
      name: letsencrypt-production
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - dns01:
          azureDNS:
            environment: AzurePublicCloud
            hostedZoneName: az.builtwithcaffine .cloud
            managedIdentity:
              clientID: "managedIdentityClientId"
            resourceGroupName: rg-builtwithcaffeine-hub-weu
            subscriptionID: b67e1026-b589-41e2-b41f-73f8803f71a0
